name: flutter_soodan_app
description: "Soodan - App médica"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # DI
  get_it: ^9.2.1
  injectable: ^2.4.4

  # Network
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0

  # Storage seguro
  flutter_secure_storage: ^10.0.0

  # Utils
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Routing
  go_router: ^17.2.0   # ⚠️ v17 requiere sdk muy reciente, usa v14 estable

  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  connectivity_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0